sh_binary(
    name = "make_gae_package",
    srcs = ["make_gae_package.sh"],
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "make_gcf_package",
    srcs = ["make_gcf_package.sh"],
    visibility = ["//visibility:public"],
)
